Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus   = "2"
    vb.memory = "2048"
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  v_HOME          = "/home/vagrant"
  v_CONFIG        = "#{v_HOME}/vm-config"
  SCRIPT_DIR      = File.expand_path("./vm-config/")

  # Make patch kubeadm available
  config.vm.synced_folder \
    "~/go/src/github.com/stealthybox/kubernetes/bazel-bin/cmd/kubeadm/linux_amd64_pure_stripped", \
    "#{v_HOME}/kubeadm"

  # add some additional config and scripts
  config.vm.synced_folder "./vm-config", v_CONFIG
  config.vm.synced_folder \
    "../intel-device-plugins-for-kubernetes", \
    "#{v_HOME}/vm-config/addon/intel-device-plugins-for-kubernetes"

  config.vm.provision "shell", privileged: true, path: "#{SCRIPT_DIR}/vm-prep.sh"

  num_controlplane = 1 # at the moment, scripts only support 1
  num_workers      = 1

  kubeadm_join_async = <<~SHELL
    set -ex
    # Join the cluster asynchronously
    source "#{v_CONFIG}/common.sh"
    nohup sh -c "
      until kubeadm join \\
        --token abcdef.0123456789abcdef \\
        --discovery-token-unsafe-skip-ca-verification \\
        192.168.5.#{10 + 1}:6443
      do sleep 2
      done
    " >> /var/log/kubeadm_join_async.log 2>&1 & disown
  SHELL

  (1..num_workers).each do |i|
    config.vm.define "worker-#{i}" do |worker|
      worker.vm.hostname = "worker-#{i}"
      worker.vm.network "private_network", ip: "192.168.5.#{100 + i}"
      worker.vm.provision "shell", inline: kubeadm_join_async
    end
  end

  (1..num_controlplane).each do |i|
    config.vm.define "controlplane-#{i}" do |controlplane|
      controlplane.vm.hostname = "controlplane-#{i}"
      controlplane.vm.network "private_network", ip: "192.168.5.#{10 + i}"
      controlplane.vm.provision "shell", path: "#{SCRIPT_DIR}/kubeadm-init.sh"
      controlplane.vm.provision "shell", path: "#{SCRIPT_DIR}/cluster-check.sh"
    end
  end
end
